### ISSUE TITLE
EDoverlay throws an exception on launch

### ISSUE THREAD

**Issue by FunGamer1999OG** [inorton/EDMCOverlay#41]
2023-05-27T21:36:27 EDMCOverlay: unhandled exception!!: Name:EDMCOverlay.exe
There are no context policies.
 System.UnhandledExceptionEventArgs
2023-05-27T21:36:27 EDMCOverlay:    at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.get_HasExited()
   at EDMCOverlay.OverlayRenderer.StartUpdate()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItem2023-05-27T21:37:49 starting..
2023-05-27T21:37:49 OverlayRenderer: Loading fonts..
2023-05-27T21:37:49 OverlayJsonServer: JSON server thread startup
2023-05-27T21:37:49 OverlayRenderer: Starting update loop
2023-05-27T21:37:49 EDMCOverlay: unhandled exception!!: Name:EDMCOverlay.exe
There are no context policies.
 System.UnhandledExceptionEventArgs
2023-05-27T21:37:49 EDMCOverlay:    at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.get_HasExited()
   at EDMCOverlay.OverlayRenderer.StartUpdate()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItem

**Comment by inorton** [comment]
I have no idea what could cause this. It is quite an old .net app now
